# Preprocessing
#Import Data
#Data Cleaning
#Data integration
#Transformasi Data
#Missing Data

In [23]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import sklearn
from numpy import math
from sklearn import preprocessing
from sklearn.preprocessing import KBinsDiscretizer
from pandas.api.types import is_float_dtype
from pandas.api.types import is_integer_dtype
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import graphviz

In [24]:
#memasukkan data
df = pd.read_excel ('D:\MyProject\RekomendasiBeasiswa\Data\BeasiswaBI.xlsx')

In [25]:
#DATA INTEGRATION
#mengganti nama record
df=df.rename(columns={
    'NR':'NR1',
    'Unnamed: 2':'NR2',
    'Unnamed: 3':'NR3',
    'Unnamed: 4':'NR4',
    'Unnamed: 5':'NR5',
    'Unnamed: 6':'NR6',
    'Unnamed: 7':'NR7',
    'Unnamed: 8':'NR8',
    'Unnamed: 9':'NR9',
    'Unnamed: 10':'NR10',
    'Unnamed: 11':'NR11'
},inplace=False)
header=list(df)

#Menggeser value column
for i in df.index:
    j=1
    if i!=0 :
        while math.isnan(float(df.loc[i, header[j]])):
            temp=df.loc[i, header[j]]
            for k in range(0,11):
                a=j+k
                b=a+1
                df.loc[i, header[a]]=df.loc[i, header[b]]
            df.loc[i, header[11]]=temp

In [26]:
#DATA REDUCTION
#Menghapus baris pertama 
df=df.drop([0])

#menghapus column
df=df.reset_index(drop=True)
for i in range(8,12):
    if df[header[i]].isnull().sum():
        del df[header[i]]
        
#Memindahkan Column
x=df.loc[:,header[0]]
del df['Status Beasiswa BI']
df = df.apply(pd.to_numeric)
df['Decision']=x
# del df['NR1']
# del df['NR2']
# del df['NR3']
# del df['NR4']
# del df['NR5']
# del df['NR6']
# del df['NR7']
df=df.reset_index(drop=True)

In [27]:
#DATA CLEANING ==> Mengisi data yang kosong dengan 
#Handling missing value
median_NR6 = df.NR6.median()
median_NR7 = df.NR7.median()
mode_Decision=df.Decision.mode()[0]
df=df.fillna({"NR6":median_NR6,"Decision":mode_Decision})
mode_Decision=df.Decision.mode()[0]
df=df.fillna({"NR7":median_NR7,"Decision":mode_Decision})
df

,NR1,NR2,NR3,NR4,NR5,NR6,NR7,IP,Penghasilan Orang Tua,Tanggungan Orang Tua,Tahun Masuk,Usia,Decision
0,3.19,3.45,2.93,2.95,2.62,3.13,3.37,3.35,1837300.0,3.0,2017.0,18.0,Iya
1,3.31,3.45,3.46,2.95,3.40,3.42,3.50,3.42,2500000.0,1.0,2017.0,19.0,Iya
2,3.83,3.61,3.86,4.00,3.82,3.94,3.83,3.72,1250000.0,4.0,2017.0,20.0,Iya
3,3.06,3.37,3.32,3.10,3.15,3.37,3.84,3.26,1000000.0,5.0,2017.0,20.0,Iya
4,3.59,3.24,3.12,3.16,3.61,3.50,3.74,3.40,1500000.0,2.0,2017.0,18.0,Iya
...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,2.95,2.65,3.03,3.33,3.24,2.90,3.89,3.00,5482100.0,4.0,2016.0,19.0,Tidak
292,3.34,3.21,3.95,3.75,3.95,3.73,4.00,3.59,5384634.0,3.0,2016.0,19.0,Tidak
293,2.97,3.37,3.48,3.46,3.55,3.14,3.64,3.29,2500000.0,4.0,2017.0,20.0,Tidak
294,3.50,3.39,3.39,3.18,3.45,3.39,3.53,3.42,300000.0,2.0,2018.0,20.0,Tidak
295,3.58,3.53,3.37,3.30,3.77,3.39,3.53,3.48,1000000.0,4.0,2018.0,18.0,Tidak

In [28]:
#DATA TRANSFORMATION ==> Diubah jadi rentang rentang kelas & Mengubah Type Data


header=list(df)
for i in range (8,12,1):
    df[header[i]]=df[header[i]].astype('int')

In [29]:
def entropy(yes,no,jumlah):
    return (-(((yes/jumlah)*(math.log2(yes/jumlah)))+((no/jumlah)*(math.log2(no/jumlah)))))
def attrGainTertinggi(entrophyKeseluruhan,attr):
    # Membagi atribut menjadi 3 group yang jumlahnya dalam satu grup sama
    attr['Bins']=pd.qcut(attr[attr.columns[0]],q=3)
    mean = attr.groupby('Bins')[attr.columns[0]].transform('mean').unique()
    Max=0
    for i in mean:
        Gain=entrophyKeseluruhan
        a1=attr[(attr[attr.columns[0]] <= i) & (attr[attr.columns[1]] == 'Iya')][attr.columns[1]].count()
        a2=attr[(attr[attr.columns[0]] <= i) & (attr[attr.columns[1]] == 'Tidak')][attr.columns[1]].count()
        a3=a1+a2
        aJumlah=attr[attr[attr.columns[0]] <= i][attr.columns[1]].count()
        b1=attr[(attr[attr.columns[0]] > i) & (attr[attr.columns[1]] == 'Iya')][attr.columns[1]].count()
        b2=attr[(attr[attr.columns[0]] > i) & (attr[attr.columns[1]] == 'Tidak')][attr.columns[1]].count()
        b3=b1+b2
        bJumlah=attr[attr[attr.columns[0]] > i][attr.columns[1]].count()
        cJumlah=aJumlah+bJumlah
        E1=entropy(a1,a2,aJumlah)
        E2=entropy(b1,b2,bJumlah)
        Gain=Gain-((a3/cJumlah*E1)+(b3/cJumlah*E2))
        if Gain>Max:
            Max=i
    return Max

In [30]:
yes=df[df.Decision == "Iya"]["Decision"].count()
no=df[df.Decision == "Iya"]["Decision"].count()
jumlah=df["Decision"].count()
Entrophy=entropy(yes,no,jumlah)

#index 0 = NR1 - Index 7 = IP
for i in range(0,9,1):
    data=df.loc[0:,[df.columns[i],'Decision']].sort_values(by=[df.columns[i]])
    ### CEK v di column, float ==> Diskret, Penghasilan ortu Diskret 9.
    if(is_float_dtype(df[df.columns[i]])):
        Max=attrGainTertinggi(Entrophy,data)
        data=data.sort_index()
        ##Ganti data/Pendiskritan
        for j,row in data.iterrows():
            if(row[0]<=Max):
                data.loc[j,[data.columns[0]]]='<='+str(Max)
            else:
                data.loc[j,[data.columns[0]]]='>'+str(Max)        
    elif (is_integer_dtype(df[df.columns[i]])):
        kategori = ['Golongan I', 
                    'Golongan II', 
                    'Golongan III',
                    'Golongan IV', 
                    'Golongan V', 
                    'Golongan VI',
                    'Golongan VII', 
                    'Golongan VIII', 
                    'Golongan IX']
        data=data.sort_index()
        data[data.columns[0]] = pd.cut(data[data.columns[0]], bins=9, labels=kategori)
    df.iloc[0:,[i]]=data.iloc[0:,[0]]  
df

,NR1,NR2,NR3,NR4,NR5,NR6,NR7,IP,Penghasilan Orang Tua,Tanggungan Orang Tua,Tahun Masuk,Usia,Decision
0,>3.023100000000002,>2.941818181818181,<=3.0298,>2.8524752475247515,<=2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan II,3,2017,18,Iya
1,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan II,1,2017,19,Iya
2,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan I,4,2017,20,Iya
3,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan I,5,2017,20,Iya
4,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan I,2,2017,18,Iya
...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,<=3.023100000000002,<=2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,<=2.949595959595959,>2.993299999999999,<=3.152199999999997,Golongan IV,4,2016,19,Tidak
292,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan IV,3,2016,19,Tidak
293,<=3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan II,4,2017,20,Tidak
294,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan I,2,2018,20,Tidak
295,>3.023100000000002,>2.941818181818181,>3.0298,>2.8524752475247515,>2.8983333333333325,>2.949595959595959,>2.993299999999999,>3.152199999999997,Golongan I,4,2018,18,Tidak

## Splitting Data

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split
##80 train, 20 test
df_train, df_test=np.split(df.sample(frac=1,random_state=42),[int(0.8*len(df))])

outcome_train = df_train.Decision.tolist()
# outcome_validation=df_validation.Decision.tolist()
outcome_test = df_test.Decision.tolist()

train_data_remove = df_train.drop(columns = "Decision")
# validation_data_remove = df_validation.drop(columns = "Decision")
test_data_remove = df_test.drop(columns = "Decision")

##80 train,10 validate,10 test
# df_train, df_validate, df_test = np.split(df.sample(frac=1,random_state=42),[int(.8*len(df)),int(.9*len(df))])

In [32]:
from chefboost import Chefboost as chef
import pandas as pd
from sklearn import tree
import graphviz

config = {'algorithm': 'C4.5'}
model = chef.fit(df_train, config = config)

C4.5  tree is going to be built...
-------------------------
finished in  10.229504108428955  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  74.57627118644068 % on  236  instances
Labels:  ['Tidak' 'Iya']
Confusion matrix:  [[65, 7], [53, 111]]
Precision:  90.2778 %, Recall:  55.0847 %, F1:  68.421 %

# Pemodelan

In [ ]:
# rules = "outputs/rules/rules.py"
# df_feature_importance = chef.feature_importance(rules).set_index("feature")
# df_feature_importance.plot(kind="barh", title="Feature Importance")

# Pruning

In [9]:
#Tidak Dapat di Pruning karena tidak dalam bentuk tree

# Testing

In [34]:
# test_array1 = chef.predict(model,train_data_remove).tolist()
# CTestAccuracy = sklearn.metrics.accuracy_score(outcome_train, test_array1)
# print('C4.5 Testing accuracy with Data Train: ',CTestAccuracy)

KeyError: 10

In [35]:
# test_array2 = model.predict(test_data_remove).tolist()
# CTestAccuracy = sklearn.metrics.accuracy_score(outcome_test, test_array2)
# print('C4.5 Testing accuracy With Data Test: ',CTestAccuracy)

In [36]:
## CEK KETEPATAN DALAM KLASIFIKASI
decision_predict=[]
TP=0
TN=0
FP=0
FN=0

for index,instance in df_test.iterrows():
#     print(instance)
    prediction = chef.predict(model, instance)
#     print(index,instance['Decision'],prediction)
#     decision_predict.append(prediction)
    if instance['Decision'] != prediction:
        if (instance['Decision'] == "Iya") and (prediction !="Iya"):
            FN+=1
        else:
            FP+=1
    else:
        if (instance['Decision'] == "Iya") and (prediction =="Iya"):
            TP+=1
        else:
            TN+=1
    print(index," ",instance['Decision'],prediction,"| TP=",TP,", TN=",TN,", FP=",FP, ", FN=",FN)
        
# df_test['Decision Predict']=decision_predict

220   Tidak Iya | TP= 0 , TN= 0 , FP= 1 , FN= 0
240   Tidak Tidak | TP= 0 , TN= 1 , FP= 1 , FN= 0
3   Iya Iya | TP= 1 , TN= 1 , FP= 1 , FN= 0
105   Iya Iya | TP= 2 , TN= 1 , FP= 1 , FN= 0
53   Iya Iya | TP= 3 , TN= 1 , FP= 1 , FN= 0
133   Iya Iya | TP= 4 , TN= 1 , FP= 1 , FN= 0
1   Iya Iya | TP= 5 , TN= 1 , FP= 1 , FN= 0
131   Iya Iya | TP= 6 , TN= 1 , FP= 1 , FN= 0
103   Iya Iya | TP= 7 , TN= 1 , FP= 1 , FN= 0
49   Iya Iya | TP= 8 , TN= 1 , FP= 1 , FN= 0
163   Tidak Tidak | TP= 8 , TN= 2 , FP= 1 , FN= 0
80   Iya Iya | TP= 9 , TN= 2 , FP= 1 , FN= 0
205   Tidak Tidak | TP= 9 , TN= 3 , FP= 1 , FN= 0
34   Iya Iya | TP= 10 , TN= 3 , FP= 1 , FN= 0
268   Tidak Iya | TP= 10 , TN= 3 , FP= 2 , FN= 0
7   Iya Iya | TP= 11 , TN= 3 , FP= 2 , FN= 0
171   Tidak Tidak | TP= 11 , TN= 4 , FP= 2 , FN= 0
198   Tidak Iya | TP= 11 , TN= 4 , FP= 3 , FN= 0
271   Tidak Iya | TP= 11 , TN= 4 , FP= 4 , FN= 0
110   Iya Iya | TP= 12 , TN= 4 , FP= 4 , FN= 0
91   Iya Iya | TP= 13 , TN= 4 , FP= 4 , FN= 0
52   Iya Iya | TP= 14 , TN= 4 , FP= 4 , FN= 0
241   Tidak Tidak | TP= 14 , TN= 5 , FP= 4 , FN= 0
13   Iya Iya | TP= 15 , TN= 5 , FP= 4 , FN= 0
88   Iya Iya | TP= 16 , TN= 5 , FP= 4 , FN= 0
166   Tidak Tidak | TP= 16 , TN= 6 , FP= 4 , FN= 0
290   Tidak Iya | TP= 16 , TN= 6 , FP= 5 , FN= 0
134   Iya Iya | TP= 17 , TN= 6 , FP= 5 , FN= 0
283   Tidak Iya | TP= 17 , TN= 6 , FP= 6 , FN= 0
243   Tidak Iya | TP= 17 , TN= 6 , FP= 7 , FN= 0
54   Iya Iya | TP= 18 , TN= 6 , FP= 7 , FN= 0
50   Iya Iya | TP= 19 , TN= 6 , FP= 7 , FN= 0
174   Tidak Tidak | TP= 19 , TN= 7 , FP= 7 , FN= 0
189   Tidak Iya | TP= 19 , TN= 7 , FP= 8 , FN= 0
294   Tidak Iya | TP= 19 , TN= 7 , FP= 9 , FN= 0
187   Tidak Iya | TP= 19 , TN= 7 , FP= 10 , FN= 0
169   Tidak Iya | TP= 19 , TN= 7 , FP= 11 , FN= 0
58   Iya Iya | TP= 20 , TN= 7 , FP= 11 , FN= 0
48   Iya Iya | TP= 21 , TN= 7 , FP= 11 , FN= 0
235   Tidak Tidak | TP= 21 , TN= 8 , FP= 11 , FN= 0
252   Tidak Iya | TP= 21 , TN= 8 , FP= 12 , FN= 0
21   Iya Tidak | TP= 21 , TN= 8 , FP= 12 , FN= 1
160   Tidak Tidak | TP= 21 , TN= 9 , FP= 12 , FN= 1
276   Tidak Iya | TP= 21 , TN= 9 , FP= 13 , FN= 1
191   Tidak Tidak | TP= 21 , TN= 10 , FP= 13 , FN= 1
257   Tidak Tidak | TP= 21 , TN= 11 , FP= 13 , FN= 1
149   Tidak Tidak | TP= 21 , TN= 12 , FP= 13 , FN= 1
130   Iya Iya | TP= 22 , TN= 12 , FP= 13 , FN= 1
151   Tidak Tidak | TP= 22 , TN= 13 , FP= 13 , FN= 1
99   Iya Iya | TP= 23 , TN= 13 , FP= 13 , FN= 1
87   Iya Iya | TP= 24 , TN= 13 , FP= 13 , FN= 1
214   Tidak Iya | TP= 24 , TN= 13 , FP= 14 , FN= 1
121   Iya Iya | TP= 25 , TN= 13 , FP= 14 , FN= 1
295   Tidak Iya | TP= 25 , TN= 13 , FP= 15 , FN= 1
20   Iya Iya | TP= 26 , TN= 13 , FP= 15 , FN= 1
188   Tidak Tidak | TP= 26 , TN= 14 , FP= 15 , FN= 1
71   Iya Iya | TP= 27 , TN= 14 , FP= 15 , FN= 1
106   Iya Iya | TP= 28 , TN= 14 , FP= 15 , FN= 1
270   Tidak Tidak | TP= 28 , TN= 15 , FP= 15 , FN= 1
102   Iya Iya | TP= 29 , TN= 15 , FP= 15 , FN= 1

In [11]:
print(TP,TN,df_test.shape[0])
CTestAccuracy=(TP+TN)/df_test.shape[0]
print('C4.5 Testing accuracy: ',CTestAccuracy)
# df=df.reset_index(drop=True)
# print(df.iloc[295:,:12].values[0])

28 10 60
C4.5 Testing accuracy:  0.6333333333333333

In [20]:
model

{'trees': [<module 'outputs/rules/rules' from 'D:\\MyProject\\RekomendasiBeasiswa\\C45\\outputs/rules/rules.py'>],
 'alphas': [],
 'config': {'algorithm': 'C4.5',
  'enableRandomForest': False,
  'num_of_trees': 5,
  'enableMultitasking': False,
  'enableGBM': False,
  'epochs': 10,
  'learning_rate': 1,
  'max_depth': 3,
  'enableAdaboost': False,
  'num_of_weak_classifier': 4,
  'enableParallelism': False,
  'num_cores': 2},
 'nan_values': [['NR1', None],
  ['NR2', None],
  ['NR3', None],
  ['NR4', None],
  ['NR5', None],
  ['IP', None],
  ['Penghasilan Orang Tua', None],
  ['Tanggungan Orang Tua', None],
  ['Tahun Masuk', None],
  ['Usia', None]]}

In [21]:
model

{'trees': [<module 'outputs/rules/rules' from 'D:\\MyProject\\RekomendasiBeasiswa\\C45\\outputs/rules/rules.py'>],
 'alphas': [],
 'config': {'algorithm': 'C4.5',
  'enableRandomForest': False,
  'num_of_trees': 5,
  'enableMultitasking': False,
  'enableGBM': False,
  'epochs': 10,
  'learning_rate': 1,
  'max_depth': 3,
  'enableAdaboost': False,
  'num_of_weak_classifier': 4,
  'enableParallelism': False,
  'num_cores': 2},
 'nan_values': [['NR1', None],
  ['NR2', None],
  ['NR3', None],
  ['NR4', None],
  ['NR5', None],
  ['IP', None],
  ['Penghasilan Orang Tua', None],
  ['Tanggungan Orang Tua', None],
  ['Tahun Masuk', None],
  ['Usia', None]]}